include:
  # Sweep
include:
  - board: nice_nano
    shield: cradio_dongle

  - board: nice_nano
    shield: cradio_left

  - board: nice_nano
    shield: cradio_right

  - board: nice_nano
    shield: settings_reset